# Import Pandas

To use the Pandas library, you need to import it into your coding environment. For these exercises, our coding environment is this Jupyter notebook. Pandas is typically imported and named as "pd".

In [2]:
# import the pandas library and use the alias 'pd'
import pandas as pd

# Series

A series is a data type used by Pandas. It is like a one dimensional list, whose elements can be of any data type themselves.
Pandas contains a method, ``.Series()``, that initiates a series object from a Python list, tuple,

In [10]:
#create the s1 series from the list: [10,20,30,40,50]
s1 = pd.Series([10,20,30,40,50])
print(s1)
print('')
# additional practice
# create a series called s_tuple from the tuple: ("apple", "banana", "cherry")
s_tuple = pd.Series(["apple", "banana", "cherry"])
print(s_tuple)
print('')
# create a series called s_dictionary from the dictionary: {"brand": "Ford", "model": "Mustang", "year": 1964}
s_dictionary = pd.Series({"brand": "Ford", "model": "Mustang", "year": 1964})
print(s_dictionary)

0    10
1    20
2    30
3    40
4    50
dtype: int64

0     apple
1    banana
2    cherry
dtype: object

brand       Ford
model    Mustang
year        1964
dtype: object

In [48]:
# fill in the blank with the series values and index values
print("The s1 series values are:", s1[0:5])
print("The s1 index values are:", s1.index)
print("\n")
print('The s_tuple series values are:',s_tuple[0:3])
print("The s_tuple index values are:",s_tuple.index)
print("\n")
print("The s_dictionary series values are:", s_dictionary[0:3])
print("The s_dictionary index values are:", s_dictionary.index)

The s1 series values are: 0    10
1    20
2    30
3    40
4    50
dtype: int64
The s1 index values are: RangeIndex(start=0, stop=5, step=1)


The s_tuple series values are: 0     apple
1    banana
2    cherry
dtype: object
The s_tuple index values are: RangeIndex(start=0, stop=3, step=1)


The s_dictionary series values are: brand       Ford
model    Mustang
year        1964
dtype: object
The s_dictionary index values are: Index(['brand', 'model', 'year'], dtype='object')

Index values in a series are generated by default. We can also define custom indexes at the time of creating series.

Below is a series of marks (grades) and the associated subjects can be defined as custom row indexes.

In [51]:
# create the s2 series from the list [80,93,78,85,97] and with labeled indexes ['English','Science','Social','Tamil','Maths']
s2 = pd.Series([80,93,78,85,97], index = ['English','Science','Social','Tamil','Maths'])

In [50]:
# print the s2 series
print(s2)

English    80
Science    93
Social     78
Tamil      85
Maths      97
dtype: int64

We can provide a name for the whole series, as well as a name for the indexes.

In [57]:
# assign the s2 series name to be "Student Marks"
#s2 = pd.Series([80,93,78,85,97], index = ['English','Science','Social','Tamil','Maths'], columns = ["Student Marks"] )
s2.name = "Student Marks"
s2 = pd.Series(s2, name = "Student Marks")
print(s2)
# assign the s2 index name to be "Subject"
s2.index.name = "Subject"

Subject
English    80
Science    93
Social     78
Tamil      85
Maths      97
Name: Student Marks, dtype: int64

In [58]:
# print the s2 series again to see the newly assigned name and index name
print(s2)

Subject
English    80
Science    93
Social     78
Tamil      85
Maths      97
Name: Student Marks, dtype: int64

## Subsetting the Series

Values inside the series can be accessed using the ``[ ]`` square bracket slicing operation

- Series can be sliced using the default index
- Series can also be sliced using string indices (indexes)

In [59]:
# return the first element in the s2 series
s2[0]

80

In [60]:
# slicing using default integer index
# return the elements starting at position one and ending with the element at index 3
s2[0:4]

Subject
English    80
Science    93
Social     78
Tamil      85
Name: Student Marks, dtype: int64

In [61]:
# Slicing using string index
# return the element associated with the index 'Tamil'
s2['Tamil']

85

## Creating a Series from a Dictionary

- A Python dictionary is a data structure which maps keys to a set of values.
- A dictionary contains key-value pairs.
- A series is similar to a dictionary in a way that it maps given indexes to a set of values.

Let's see how to create a series from a dictionary

I have a dictionary that represents fruits and prices. Let's create a series from this dictionary

In [63]:
# create a dictionary of fruit names and their prices. Use the values from the article
dict_fruits = { 'Orange':80,
          'Apples':210,
          'Bananas':50,
         'Grapes':90,
         'Watermelon':70}

In [64]:
# Lets convert this dictionary into a series
# use the pandas method .Series() 
fruits = pd.Series(dict_fruits)

In [66]:
# print the series
print(fruits)

Orange         80
Apples        210
Bananas        50
Grapes         90
Watermelon     70
dtype: int64

In [65]:
# Slice the series and retrieve price of grapes
fruits["Grapes"]

90

# DataFrame

## Create a DataFrame from a Series object

Let's create a DataFrame from the marks series we created in the above step.

In [82]:
# create a dataframe from the s2 series
fruits_Df = pd.DataFrame({"fruits":fruits})

In [83]:
# print the dataframe
print(fruits_Df)

            fruits
Orange          80
Apples         210
Bananas         50
Grapes          90
Watermelon      70

## Create a DataFrame from a Dictionary

Let's say we have 2 series of heights and weights of the same set of persons and we want to put it together in a table.

Here we can create dictionary using both series and create a DataFrame using the Pandas ``.DataFrame()`` method.

In [77]:
# Create height series using [5.3, 6.2,5.8,5.0,5.5] for values, ['Person 1','Person 2','Person 3','Person 4','Person 5'] for indexes
height = pd.Series([5.3, 6.2,5.8,5.0,5.5], index = ['Person 1','Person 2','Person 3','Person 4','Person 5'])
print(height)
print('\n')
# Create weight series (in kgs) using [65,89,75,60,59] for values and the same indexes as height
weight = pd.Series([65,89,75,60,59], index = ['Person 1','Person 2','Person 3','Person 4','Person 5'])
print(weight)

Person 1    5.3
Person 2    6.2
Person 3    5.8
Person 4    5.0
Person 5    5.5
dtype: float64


Person 1    65
Person 2    89
Person 3    75
Person 4    60
Person 5    59
dtype: int64

In [73]:
# Create a dataframe from the height and weight series above

# print the dataframe

In [81]:
newDf = pd.DataFrame({"height":height, "weight":weight})
print(newDf)

          height  weight
Person 1     5.3      65
Person 2     6.2      89
Person 3     5.8      75
Person 4     5.0      60
Person 5     5.5      59